FROM nginx:latest
COPY static/css /usr/share/nginx/html/css
COPY static/js /usr/share/nginx/html/js
COPY static/images /usr/share/nginx/html/img
# COPY templates /usr/share/nginx/html/templates

# COPY ../demo/src/main/resources/static/css /usr/share/nginx/html/css
# COPY ../demo/src/main/resources/static/js /usr/share/nginx/html/js
# COPY ../demo/src/main/resources/static/img /usr/share/nginx/html/img